language: nix
env:
  - EMACS_CI=emacs-25-1
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-3
before_install:
  # nix-emacs-ci
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

  # cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

  # rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env

  # ripgrep
  - cargo install ripgrep
install:
  - make deps
script:
  - emacs --version
  - make test
